squid:
  image: sameersbn/squid:3.5.27-2
  ports:
    - "3128:3128"
  volumes:
    - ./.cache:/var/spool/squid
    - ./.logs:/var/log/squid
    - ./conf/squid.conf:/etc/squid/squid.conf
    - ./conf/passwd:/etc/squid/passwd
